### ISSUE TITLE
project tests

### ISSUE THREAD

**Issue by Diane513** [half-dreamer/CS61A-20fa#1]
想问下博主，在做projects时有没有遇到做了tests，并且看到了'OK! All cases for Question 1 unlocked.' 却还被lock的情况。

`$ python3 ok -q 01
=====================================================================
Assignment: Project 1: Hog
OK, version v1.18.1
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests


There are still locked tests! Use the -u option to unlock them
---------------------------------------------------------------------
Test summary
    Locked: 6
    0 test cases passed! No cases failed.

Performing authentication
Please enter your school email (.edu):`

**Comment by half-dreamer** [comment]
没有哎，你可以按照提示写的-u来unlock

Diane513 ***@***.***> 于2023年6月26日周一 14:20写道：

**Comment by Diane513** [comment]
谢谢回答~ 
我是按照官方网页上的第一步'python3 ok -q 01 -u'，并且到了’OK! All cases for Question 1 unlocked.',  第二步'python3 ok -q 01', 却还是显示tests locked. 
我疑惑是不是因为-u之后没有登录邮箱呀，我是直接Ctrl-Z。请问你是有登录邮箱吗

**Comment by half-dreamer** [comment]
是的，我有登录邮箱，好像是用Gmail还是学校自己的教育邮箱我忘了，可以都试试

Diane513 ***@***.***> 于2023年6月27日周二 09:37写道：

**Comment by Diane513** [comment]
谢谢回答~
